#!/bin/bash

if [ ! -d ".git" ]; then
	echo "Please run this script from your repository root folder"
	exit 1
fi;

git config --local include.path ../.git-local/config

declare -a hooks=(commit-msg prepare-commit-msg pre-push)

# Instal hooks
for hook in "${hooks[@]}"; do
	ln -sf "$(PWD)/.git-local/hooks/${hook}" "$(PWD)/.git/hooks/${hook}"
	chmod +x ".git/hooks/${hook}"
done
